/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 balonPolyhedra.gltf
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/icosub-4a97eed274614afe964698547cf4ef73
Title: IcoSub
*/

import { useGLTF } from '@react-three/drei'

export default function ModelBalonPolyhedra(props) {
  const { nodes, materials } = useGLTF('/balonPolyhedra.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/balonPolyhedra.gltf')
