/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 balonLeather.gltf
Author: MAMA's Sneaker Stop (https://sketchfab.com/mamasneakers)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/leather-foot-ball-soccer-408c38d8b34f49c18d1424fa8abd67a8
Title: Leather Foot Ball "Soccer"
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

export default function ModelBaloLeather(props) {
  const { nodes, materials } = useGLTF('/balonLeather.gltf')
  const modelRef = useRef()

  // Rota el modelo sobre su propio eje
  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.0051
    }
  })

  return (
    <group ref={modelRef} {...props} dispose={null}>
      <group position={[-28.428, 292.05, -147.699]} rotation={[0.634, 0, Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.soccer_group_DefaultMaterial_0.geometry} material={materials.DefaultMaterial} position={[-14.214, 190.537, 14.258]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/balonLeather.gltf')
