/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 balonShell.gltf
Author: israfitul (https://sketchfab.com/israfitul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shell-light-ball-0ef01b42b7e1456c8b79a25f805ab71a
Title: shell light ball
*/

import { useGLTF } from '@react-three/drei'

export default function ModelBalonShell(props) {
  const { nodes, materials } = useGLTF('/balonShell.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -1.565, Math.PI]} scale={0.029}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/balonShell.gltf')